SLIDESDOC-197: Added macOS installation instructions
aspose-slides/Aspose.Slides-Documentation pull request #232
Opened 2021-09-06 11:00 UTC by EmSeriki

I added instructions for installing Aspose.Slides in macOS and reviewed the installation page.

2021-09-10 07:26 UTC, stasmiroshnichenko requested changes
@EmSeriki please don't use whitespaces in file names. Use "-" instead. File "Path to NuGet mac.png" should be renamed.

2021-09-16 07:59 UTC, stasmiroshnichenko approved these changes

2021-09-16 12:16 UTC, yury-knml approved these changes

2021-09-17 07:21 UTC, victorkrivolapaspose approved these changes

2021-09-17 07:35 UTC, merged