SLIDESNET-42807 - Add article for SLIDESNET-42689
aspose-slides/Aspose.Slides-Documentation pull request #242
Opened 2021-09-19 12:13 UTC by MaxChuryumov

Added the CalulateFormulas method mention. Added missing code examples.

2021-09-21 17:40 UTC, EmSeriki approved these changes

2021-09-22 09:57 UTC, stasmiroshnichenko commented
@MaxChuryumov @EmSeriki 
Unable to merge changes. Please resolve conflicts.

2021-09-22 10:06 UTC, stasmiroshnichenko requested changes
@MaxChuryumov @EmSeriki Please resolve conflicts.

2021-09-28 12:52 UTC, yury-knml approved these changes

2021-09-29 08:55 UTC, stasmiroshnichenko approved these changes

2021-09-29 08:55 UTC, merged