SLIDESDOC-165 How to take the image of a paragraph
aspose-slides/Aspose.Slides-Documentation pull request #654
Opened 2024-10-22 07:21 UTC by andreypotapovaspose

Updated keywords and added the section "Save a Paragraph as an Image" to the article "Manage PowerPoint Paragraph".

2024-10-28 12:08 UTC, nikolaysaulyak approved these changes

2024-10-30 11:55 UTC, petrtetenko requested changes
I also prepared an article for the nodejs.

[_index.md](https://github.com/user-attachments/files/17571810/_index.md)

2024-10-31 07:31 UTC, valentynlukianets-aspose approved these changes
Approved C++ and Python via .NET

2024-10-31 09:38 UTC, petrtetenko approved these changes

2024-10-31 09:44 UTC, merged