SLIDESNET-42342 - Add article for SLIDESNET-36994
aspose-slides/Aspose.Slides-Documentation pull request #7
Opened 2020-12-23 19:00 UTC by MaxChuryumov

https://issue.lutsk.dynabic.com/issues/SLIDESNET-42342

2021-01-18 18:31 UTC, stasmiroshnichenko reviewed
Please see my comments.
You can check your changes directly in GitHub https://github.com/aspose-slides/Aspose.Slides-Documentation/blob/SLIDESNET-42342/net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md

2021-01-18 18:31 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +  * [Add Custom Points to the Shape](#add-custom-points-to-the-shape-)
The navigation link is not working
Please change  #add-custom-points-to-the-shape- to #add-custom-points-to-the-shape

2021-01-18 18:31 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +  * [Remove Points From the Shape](#remove-points-from-the-shape-)
The navigation link is not working

2021-01-18 18:31 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +  * [Conversion of GeometryPath to GrpahicsPath (System.Drawing.Drawing2D)](#-onversion-of-geometrypath-to-grpahicspath--systemdrawingdrawing2d-)
The navigation link is not working 
typo #-onversion, it should be #conversion

2021-01-18 18:31 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +- Retrieve an instance of the [GeometryPath]() class from the shape
empty link [GeometryPath](), is it correct?

2021-01-19 15:44 UTC, stasmiroshnichenko approved these changes

2021-01-20 06:57 UTC, stasmiroshnichenko requested changes

2021-01-20 06:57 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +   void CubicBezierTo(float x1, float y1, float x2, float y2, float x3, float y3, uint index);
extra tab

2021-01-20 06:57 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +    void CloseFigure();
extra tab

2021-01-20 06:57 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +    void ArcTo(float width, float heigth, float startAngle, float sweepAngle);
extra tab

2021-01-20 06:57 UTC, stasmiroshnichenko commented on net/developer-guide/presentation-content/powerpoint-shapes/shape-types/custom-shapes/_index.md
> +void LineTo(PointF point, uint index)
a semicolon is missed at the end of the line

2021-01-20 07:38 UTC, stasmiroshnichenko approved these changes

2021-01-20 09:25 UTC, yury-knml approved these changes

2021-01-20 12:09 UTC, agrazhevskaja requested changes
@MaxChuryumov Please, review my comments under your commits and fix them. Thank you

2021-01-21 10:24 UTC, agrazhevskaja approved these changes

2021-01-21 10:30 UTC, merged