SLIDESDOC-42--Changes for the SVG article
aspose-slides/Aspose.Slides-Documentation pull request #88
Opened 2021-05-31 17:47 UTC by EmSeriki

I rewrote the article from scratch, added the new code sample Yura provided, deleted the image that was no longer showing, deleted the "Download Sample Code" section (because I changed the sample code), moved the article to a better location, and so on. 

I still left a copy of the article in the original (wrong) location... in case we have readers that still go there (or to avoid breaking old links).

2021-06-01 07:09 UTC, stasmiroshnichenko requested changes
Emmanuel, you have submitted 2 pages with identical URLs in the Hugo settings sections:
 - net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-slide-as-svg-image/_index.md (url: /net/render-slide-as-svg-image/)
 - net/plugins/aspose-slides-for-openxml/missing-features-in-openxml/rendering-and-printing-of-presentation/render-slide-as-svg-image/_index.md (url: /net/render-slide-as-svg-image/)
 
We should use different URLs for correct public site behavior. Please change the URL for the new page.

2021-06-02 09:12 UTC, yury-knml approved these changes

2021-06-02 13:37 UTC, EmSeriki commented
> Emmanuel, you have submitted 2 pages with identical URLs in the Hugo settings sections:
> 
> * net/developer-guide/manage-presentation/convert-presentation/convert-powerpoint/render-slide-as-svg-image/_index.md (url: /net/render-slide-as-svg-image/)
> * net/plugins/aspose-slides-for-openxml/missing-features-in-openxml/rendering-and-printing-of-presentation/render-slide-as-svg-image/_index.md (url: /net/render-slide-as-svg-image/)
> 
> We should use different URLs for correct public site behavior. Please change the URL for the new page.

I've changed the article's name and path. Thank you.

2021-06-02 14:40 UTC, stasmiroshnichenko approved these changes

2021-06-02 14:40 UTC, merged